In [1]:
# Import des données

import pandas as pd
import os
import load_data.donnees_chargement
parite = load_data.donnees_chargement.load_parite()
parite

/home/onyxia/work/Projet_python_2A/load_data/donnees_chargement.py:29: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  parite['week_day_number'] = parite['week_day'].replace({

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration,week_day_number
636822,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,12,829.06,371.28,2056.80,5
636823,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,14,148.42,68.56,2993.40,5
636824,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,18,1722.84,307.90,1238.96,5
636825,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,21,2714.88,329.62,286.16,5
636826,tv,ART,ARTE,True,2010-01-02,Saturday,ABC,False,11,1254.78,1243.14,1070.86,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013627,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,19,1261.04,1343.74,826.58,4
1013628,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,20,1738.18,1304.92,477.12,4
1013629,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,21,1841.44,818.52,850.54,4
1013630,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,22,1817.82,747.30,972.06,4
1013631,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,23,1748.44,669.12,996.64,4

In [1]:
# Sélection des chaines FR2, FR3, TF1, M6 et Arte

parite_tv = parite[parite['channel_code'].isin(['TF1', 'M6', 'FR2', 'FR3', 'ART'])]
parite_tv['channel_code'].unique()
parite_tv.head()
os.remove('temp.csv')

NameError: name 'parite' is not defined

In [6]:
# Calcul du temps de parole masculin et fémnin par chaine et jour de la semaine


parite_jour_chaine = parite_tv.groupby(['channel_code', 'week_day_number']).agg(
    week_day = ('week_day', 'first'),
    channel_name = ('channel_name', 'first'),
    female_duration = ('female_duration', 'sum'),
    male_duration = ('male_duration', 'sum')
).reset_index()

parite_jour_chaine['proportion_female'] = parite_jour_chaine['female_duration'] / (parite_jour_chaine['female_duration'] + parite_jour_chaine['male_duration'])

parite_jour_chaine[['week_day', 'channel_name', 'proportion_female']]

     week_day channel_name  proportion_female
0      Monday         ARTE           0.286243
1     Tuesday         ARTE           0.295038
2   Wednesday         ARTE           0.287536
3    Thursday         ARTE           0.299171
4      Friday         ARTE           0.295776
5    Saturday         ARTE           0.287434
6      Sunday         ARTE           0.291904
7      Monday     France 2           0.387602
8     Tuesday     France 2           0.376124
9   Wednesday     France 2           0.376600
10   Thursday     France 2           0.370374
11     Friday     France 2           0.368843
12   Saturday     France 2           0.280098
13     Sunday     France 2           0.235764
14     Monday     France 3           0.310406
15    Tuesday     France 3           0.323461
16  Wednesday     France 3           0.313541
17   Thursday     France 3           0.307661
18     Friday     France 3           0.312962
19   Saturday     France 3           0.355951
20     Sunday     France 3           0.306340
21     Monday           M6           0.435392
22    Tuesday           M6           0.428768
23  Wednesday           M6           0.420163
24   Thursday           M6           0.423158
25     Friday           M6           0.422101
26   Saturday           M6           0.412810
27     Sunday           M6           0.343837
28     Monday          TF1           0.391162
29    Tuesday          TF1           0.373408
30  Wednesday          TF1           0.374925
31   Thursday          TF1           0.379142
32     Friday          TF1           0.380492
33   Saturday          TF1           0.368022
34     Sunday          TF1           0.287258