In [1]:
# Import des données

import pandas as pd
import load_data.donnees_chargement
parite = load_data.donnees_chargement.load_parite()
parite

/home/onyxia/work/Projet_python_2A/load_data/donnees_chargement.py:26: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  parite['week_day_number'] = parite['week_day'].replace({

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration,week_day_number
636822,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,12,829.06,371.28,2056.80,5
636823,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,14,148.42,68.56,2993.40,5
636824,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,18,1722.84,307.90,1238.96,5
636825,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,21,2714.88,329.62,286.16,5
636826,tv,ART,ARTE,True,2010-01-02,Saturday,ABC,False,11,1254.78,1243.14,1070.86,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1013627,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,19,1261.04,1343.74,826.58,4
1013628,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,20,1738.18,1304.92,477.12,4
1013629,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,21,1841.44,818.52,850.54,4
1013630,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,22,1817.82,747.30,972.06,4
1013631,tv,TF1,TF1,False,2019-02-28,Thursday,AC,False,23,1748.44,669.12,996.64,4

In [2]:
# Sélection des chaines FR2, FR3, TF1, M6 et Arte

parite_tv = parite[parite['channel_code'].isin(['TF1', 'M6', 'FR2', 'FR3', 'ART'])]
parite_tv['channel_code'].unique()
parite_tv.head()

,media_type,channel_code,channel_name,is_public_channel,date,week_day,school_holiday_zones,civil_holyday,hour,male_duration,female_duration,music_duration,week_day_number
636822,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,12,829.06,371.28,2056.80,5
636823,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,14,148.42,68.56,2993.40,5
636824,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,18,1722.84,307.90,1238.96,5
636825,tv,ART,ARTE,True,2010-01-01,Friday,ABC,True,21,2714.88,329.62,286.16,5
636826,tv,ART,ARTE,True,2010-01-02,Saturday,ABC,False,11,1254.78,1243.14,1070.86,6

In [4]:
# Calcul du temps de parole masculin et fémnin par chaine et jour de la semaine


parite_jour_chaine = parite_tv.groupby(['channel_code', 'week_day_number']).agg(
    week_day = ('week_day', 'first'),
    channel_name = ('channel_name', 'first'),
    female_duration = ('female_duration', 'sum'),
    male_duration = ('male_duration', 'sum')
).reset_index()

parite_jour_chaine['proportion_female'] = parite_jour_chaine['female_duration'] / (parite_jour_chaine['female_duration'] + parite_jour_chaine['male_duration'])

parite_jour_chaine.head(100)

,channel_code,week_day_number,week_day,channel_name,female_duration,male_duration,proportion_female
0,ART,1,Monday,ARTE,1694968.80,4226459.64,0.286243
1,ART,2,Tuesday,ARTE,1846689.30,4412469.50,0.295038
2,ART,3,Wednesday,ARTE,1734310.62,4297328.58,0.287536
3,ART,4,Thursday,ARTE,1786337.68,4184621.72,0.299171
4,ART,5,Friday,ARTE,1782345.06,4243650.80,0.295776
5,ART,6,Saturday,ARTE,1771217.10,4390961.62,0.287434
6,ART,7,Sunday,ARTE,1578945.68,3830172.12,0.291904
7,FR2,1,Monday,France 2,2548642.34,4026767.24,0.387602
8,FR2,2,Tuesday,France 2,2536226.94,4206827.40,0.376124
9,FR2,3,Wednesday,France 2,2428847.00,4020569.08,0.376600
10,FR2,4,Thursday,France 2,2533047.54,4306106.60,0.370374
11,FR2,5,Friday,France 2,2397420.24,4102415.88,0.368843
12,FR2,6,Saturday,France 2,1744465.16,4483597.18,0.280098
13,FR2,7,Sunday,France 2,1468342.94,4759681.46,0.235764
14,FR3,1,Monday,France 3,1924873.48,4276282.96,0.310406
15,FR3,2,Tuesday,France 3,2122368.20,4439066.28,0.323461
16,FR3,3,Wednesday,France 3,2045147.74,4477594.78,0.313541
17,FR3,4,Thursday,France 3,1956686.94,4403190.56,0.307661
18,FR3,5,Friday,France 3,1987155.76,4362362.30,0.312962
19,FR3,6,Saturday,France 3,2226035.38,4027739.90,0.355951
20,FR3,7,Sunday,France 3,1872868.20,4240821.72,0.306340
21,M6,1,Monday,M6,2487538.58,3225796.92,0.435392
22,M6,2,Tuesday,M6,2555772.34,3404966.62,0.428768
23,M6,3,Wednesday,M6,2469579.34,3408093.22,0.420163
24,M6,4,Thursday,M6,2547793.74,3473116.78,0.423158
25,M6,5,Friday,M6,2461087.08,3369475.96,0.422101
26,M6,6,Saturday,M6,2609797.80,3712227.52,0.412810
27,M6,7,Sunday,M6,2194512.56,4187915.98,0.343837
28,TF1,1,Monday,TF1,2350712.32,3658855.02,0.391162
29,TF1,2,Tuesday,TF1,2255894.04,3785473.18,0.373408
30,TF1,3,Wednesday,TF1,2281018.54,3802909.16,0.374925
31,TF1,4,Thursday,TF1,2306943.32,3777700.10,0.379142
32,TF1,5,Friday,TF1,2344950.42,3817988.28,0.380492
33,TF1,6,Saturday,TF1,2309681.04,3966258.82,0.368022
34,TF1,7,Sunday,TF1,1738536.46,4313632.46,0.287258